-- Phase 1: seed the industries lookup from the workbook's Industries sheet
-- (the curated Keep=YES column, deduplicated case-insensitively; 171 names).
-- 'Accountant' already exists live, hence ON CONFLICT DO NOTHING.

INSERT INTO industries (name) VALUES
  ('Accountant'),
  ('Agriculture'),
  ('Agriculture: Building Material'),
  ('Agriculture: Equipment'),
  ('Animal Hospital'),
  ('Apparel'),
  ('Assisted Living'),
  ('Auto Body'),
  ('Auto Detailing'),
  ('Auto Sales'),
  ('Automotive'),
  ('Automotive Repair'),
  ('Automotive: Trailer Sales'),
  ('Baked Goods Stores'),
  ('Bakery'),
  ('Beauty Shop'),
  ('Beer and Ale Merchant Wholesalers'),
  ('Brewing'),
  ('Business Services'),
  ('Cabinet Manufacturer'),
  ('Cannabis Retail'),
  ('Car Hauling'),
  ('Carpet & Flooring'),
  ('Charter Services'),
  ('Chiropractic Services'),
  ('Consignment'),
  ('Construction'),
  ('Construction: Cabinetry'),
  ('Construction: Concrete'),
  ('Construction: Excavation'),
  ('Construction: Fiber Optic'),
  ('Construction: Flooring'),
  ('Construction: Gen Contractor'),
  ('Construction: Grading'),
  ('Construction: Infrastructure'),
  ('Construction: Painting'),
  ('Construction: Pool'),
  ('Construction: Re-modeling'),
  ('Construction: Restoration'),
  ('Construction: Roofing'),
  ('Construction: Special Trade'),
  ('Construction: Specialty'),
  ('Construction: Stone'),
  ('Construction: Trucking'),
  ('Consulting'),
  ('Contracting'),
  ('Convenience Store'),
  ('Cosmetics'),
  ('Dance Studio'),
  ('Day Care'),
  ('Debris Collection'),
  ('Dentistry'),
  ('Digital Marketing'),
  ('Door Sales, Repair and Install'),
  ('Drilling Services'),
  ('E-Commerce'),
  ('Education'),
  ('Education Services'),
  ('Electrician'),
  ('Elevator Servicing'),
  ('Energy'),
  ('Engineering Services'),
  ('Entertainment'),
  ('Equipment Rental'),
  ('Equipment Sales'),
  ('Event Planning'),
  ('Farm Equip'),
  ('Farmers Market'),
  ('Farming'),
  ('Fencing'),
  ('Financial Services'),
  ('Fitness'),
  ('Fitness Studios'),
  ('Flooring & Tile'),
  ('Food Distributor'),
  ('Food Truck'),
  ('Forensic Services'),
  ('Foster Care Agency'),
  ('Foundation Drilling'),
  ('Furniture'),
  ('Furniture Manufacturers'),
  ('Gas Station'),
  ('Geriatric'),
  ('Gov''t Contractor'),
  ('Gym'),
  ('Hair Salon'),
  ('Health Spa'),
  ('Healthacare: Home'),
  ('Healthcare'),
  ('Healthcare (Med Office)'),
  ('Heat Exchanger Plates and Gaskets'),
  ('Home Care: Medical'),
  ('Home Care: Non Medical'),
  ('Home Health'),
  ('Hospice Care'),
  ('Hospitality'),
  ('Hospitality: Hotel'),
  ('HVAC'),
  ('HVAC/Plumbing'),
  ('Immigration Services'),
  ('Importer: Perfume'),
  ('Insurance'),
  ('IT Consulting'),
  ('IT Services'),
  ('Janitorial'),
  ('Jeweler'),
  ('Junk Removal'),
  ('Landscaping'),
  ('Law Firm'),
  ('Legal'),
  ('Legal Services'),
  ('Liquor Store'),
  ('Mail Carrier'),
  ('Manufacturing'),
  ('Marine'),
  ('Marketing Consulting'),
  ('Media (Print)'),
  ('Medical'),
  ('Medical Consultant'),
  ('Medical Device'),
  ('Medical Office'),
  ('Medical Transportation'),
  ('Medical: EMS'),
  ('Nail Salon'),
  ('Nutraceuticals'),
  ('Optometrist'),
  ('Painting'),
  ('Personal Services'),
  ('Pharmaceutical'),
  ('Pharmacy'),
  ('Photography'),
  ('Plumbing'),
  ('Pool Services'),
  ('Property Mgt'),
  ('Real Estate Rentals'),
  ('Real Estate Services'),
  ('Real Estate Technology'),
  ('Restaurant'),
  ('Restaurant Brewery'),
  ('Restaurant Franchise'),
  ('Restoration'),
  ('Retail'),
  ('Retail - Furniture'),
  ('Retail / Wholesale'),
  ('Retail: Wine & Liquor'),
  ('RIA'),
  ('Safety Equipment'),
  ('Scientific & Tech Services'),
  ('Security'),
  ('Security Services'),
  ('Senior Care'),
  ('Septic Services'),
  ('Smoke Shop'),
  ('Software'),
  ('Specialty Grocery Store'),
  ('Technology'),
  ('Telecommunications'),
  ('Tire Shop'),
  ('Towing'),
  ('Transportation'),
  ('Transportation Services'),
  ('Travel'),
  ('Tree Cutting'),
  ('Truck Parts'),
  ('Truck Repair'),
  ('Trucking'),
  ('Trucking & Agricultural Supplies'),
  ('Vending'),
  ('Wholesale'),
  ('Wholesale Durable Goods'),
  ('Wine Distribution')
ON CONFLICT (name) DO NOTHING;
